// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmrcrrcauhrygiccazpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcmNycmNhdWhyeWdpY2NhenB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNDYxNjEsImV4cCI6MjA4NDkyMjE2MX0.jUqvU4kjzeXbR6j7Nz08_I9RNha-WrjvACXbO-tZ_BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});